---
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude_types: ['markdown']
        stages: [pre-commit]
      - id: trailing-whitespace
        exclude_types: ['markdown']
        stages: [pre-commit]
      - id: mixed-line-ending
        stages: [pre-commit]
      - id: check-byte-order-marker
        stages: [pre-commit]
      - id: check-executables-have-shebangs
        stages: [pre-commit]
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: helm-docs
        name: helm-docs
        entry: make
        args: ["helm-docs"]
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: ct-lint
        name: ct-lint
        entry: make
        args: ["helm-lint"]
        language: system
        pass_filenames: false
        stages: [pre-commit]
