apiVersion: v2
name: vcluster
description: Virtual Kubernetes Cluster
type: application
version: 0.13.0
appVersion: 0.1.0
keywords:
  - vcluster
  - kubernetes
  - machine-controller
  - kubermatic
home: https://artifacthub.io/packages/helm/kvaps/kubernetes
maintainers:
  - name: "Bedag Informatik AG"
    email: sre@bedag.ch
dependencies:
  - name: common
    version: 2.14.1
    repository: oci://registry-1.docker.io/bitnamicharts
