{{- define "common.ingress.secret" -}}
{{- $root := . }}
{{- $ingresses := .Values.ingresses }}
{{- range $ingress := $ingresses }}
{{- $cert := "" }}
{{- if $ingress }}
{{- if $ingress.deploy }}
{{- if eq $ingress.tls.type "self" }}
{{- $cert = genSelfSignedCert ($ingress.tls.self.commonName) (default nil $ingress.tls.self.ipAddresses) (default nil $ingress.tls.self.alternativeDnsNames) ($ingress.tls.self.validityDuration | int) }}
{{- else if eq $ingress.tls.type "provided" }}
{{- $cert = buildCustomCert $ingress.tls.provided.cert $ingress.tls.provided.key }}
{{- end }}
{{ if or (eq $ingress.tls.type "self") (eq $ingress.tls.type "provided")}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "library.name" $root }}-ingress-tls
  labels:
{{ include "library.labels.standard" $root | indent 4 }}
    app.kubernetes.io/component: ingress-tls
type: Opaque
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
