{{- define "common.ingress.ingress" -}}
{{- $root := . }}
{{- $ingresses := .Values.ingresses }}
{{- range $name, $ingress := $ingresses }}
{{- if $ingress.deploy }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "library.name" $root }}-{{$name}}
  labels:
{{ include "library.labels.standard" $root | indent 4 }}
    app.kubernetes.io/component: ingress
{{- if $ingress.annotations }}
  annotations:
{{ toYaml $ingress.annotations | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ $ingress.ingressClassName }}
  {{- if $ingress.defaultBackend }}
  {{- if not $ingress.rules }}
  defaultBackend:
    service:
      name: {{ template "library.name" $root }}-{{ $ingress.defaultBackend.serviceNameSuffix }}
      port:
        {{- if kindIs "float64" $ingress.defaultBackend.servicePort }}
        number: {{ $ingress.defaultBackend.servicePort }}
        {{- else }}
        name: {{ $ingress.defaultBackend.servicePort | quote }}
        {{- end }}
  {{- end }}
  {{- end }}
  {{- if not $ingress.defaultBackend }}
  rules:
    {{- range $ingress.rules }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .http.paths }}
          - backend:
              service:
                name: {{ template "library.name" $root }}-{{ .backend.serviceNameSuffix }}
                port:
                  {{- if kindIs "float64" .backend.servicePort }}
                  number: {{ .backend.servicePort }}
                  {{- else }}
                  name: {{ .backend.servicePort | quote }}
                  {{- end }}
            path: {{ .path | default "/" | quote }}
            pathType: {{ .pathType | default "ImplementationSpecific" | quote }}
          {{- end }}
    {{- end }}
  {{- if $ingress.tls }}
  {{- if and (ne $ingress.tls.type "none") (ne $ingress.tls.type "") }}
  tls:
    {{- range $ingress.rules }}
    - hosts:
        - {{ .host }}
      {{- if or (eq $ingress.tls.type "self") (eq $ingress.tls.type "provided") }}
      secretName:  {{ regexReplaceAll "\\W+" .host "-" }}
      {{- else if eq $ingress.tls.type "existing" }}
      secretName: {{ .secretName }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end -}}
