{{- if $.Values.global.components.exposure.certificates.issuer.selfSigned }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name:  {{ include "pkg.components.certificates.default_issuer" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vcluster.labels" $ | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
