{{/*
  Always Create Manifests Secret.
  This way the in cluster resources can be removed if a component is disabled
*/}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operating-system-manager.manifests.name" $ }}
  labels:
    {{- include "operating-system-manager.labels" . | nindent 4 }}
stringData:
  {{ range $path, $_ := .Files.Glob (include "operating-system-manager.manifests" $) }}
    {{- with $ }}
      {{- $content := (tpl (.Files.Get $path) .) -}}
      {{- if ($content | nospace) }}
        {{- base $path | nindent 4 }}: | {{- $content | nindent 6 }}
      {{- end }}
    {{ end }}
  {{- end }}
