{{/*
  Always Create Webhook secret.
  This way the in cluster resources can be removed if a component is disabled
*/}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "machine-controller.fullname" . }}-webhooks
  labels: {{- include "machine-controller.labels" . | nindent 4 }}
stringData:
  {{ range $path, $_ := .Files.Glob (include "machine-controller.webhooks" $) }}
    {{- with $ }}
      {{- base $path | nindent 4 }}: | {{- tpl (.Files.Get $path) . | nindent 6 }}
    {{ end }}
  {{- end }}
