{{- $manifest := $.Values.jobs -}}
{{- if $manifest.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vcluster.serviceAccountName" . }}
  labels:
    {{- include "vcluster.labels" . | nindent 4 }}
  {{- with $manifest.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
